env:
  - IMAGE_NAME=finstreet/test-deployment

services:
  - docker

before_install:
  - docker build -t $IMAGE_NAME:latest-travis .
  - echo $DOCKER_USERNAME
  - docker push $IMAGE_NAME:latest-travis
