language: minimal

env:
  - IMAGE_NAME=finstreet/test-deployment

services:
  - docker

  - add_ssh_keys:
    fingerprints:
      - "af:06:17:c7:98:0c:6d:b9:51:47:36:39:9a:31:da:9a"

script:
  - ssh-keyscan -H 94.130.59.82 >> ~/.ssh/known_hosts
  - ssh $SSH_USER@$SSH_HOST 'cd /var/Wordpress/ && ./restart.sh'

before_install:
  - docker build -t $IMAGE_NAME:latest-travis .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $IMAGE_NAME:latest-travis