env:
  - IMAGE_NAME=finstreet/test-deployment

services:
  - docker

before_install:
  - docker build -t $IMAGE_NAME:latest-travis .
  - docker login -u "$DOCKER_USERNAME" --password-stdin. "$DOCKER_PASSWORD"
  - docker push $IMAGE_NAME:latest-travis
