env:
  - IMAGE_NAME=finstreet/test-deployment

services:
  - docker

before_install:
  - docker build -t $IMAGE_NAME:latest-travis .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $IMAGE_NAME:latest-travis
