dist: trusty

env:
  - IMAGE_NAME=finstreet/test-deployment

jobs:
  include:
    - stage: build docker image
      script:
      - echo docker docker build -t $IMAGE_NAME:latest .
      - echo docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push $IMAGE_NAME:latest
