language: minimal

env:
- IMAGE_NAME=finstreet/test-deployment

services:
- docker

git:
  depth: 25
  quiet: true

addons:
  ssh_known_hosts:
  - 94.130.59.82
  
before_deploy:
  - openssl aes-256-cbc -K $encrypted_6f340cccd9a6_key -iv $encrypted_6f340cccd9a6_iv
    -in deploy_travis_rsa.enc -out /tmp/deploy_travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_travis_rsa
  - ssh-add /tmp/deploy_travis_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ssh $SSH_USER@$SSH_HOST 'cd /var/Wordpress/ && ./restart.sh'

before_install:
  - docker build -t $IMAGE_NAME:latest-Travis-$TRAVIS_QUEUE_BRANCH .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $IMAGE_NAME:latest-Travis-$TRAVIS_QUEUE_BRANCH