env:
  - IMAGE_NAME=finstreet/test-deployment

services:
  - docker

before_install:
  - echo docker build -t $IMAGE_NAME:latest-travis .
  - echo docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - echo docker push $IMAGE_NAME:latest-travis

script:
  - bundle exec rake test
