language: minimal

env:
  - IMAGE_NAME=finstreet/test-deployment

services:
  - docker

addons:
  ssh_known_hosts:
    - 94.130.59.82

script:
  - ssh $SSH_USER@$SSH_HOST 'cd /var/Wordpress/ && ./restart.sh'

before_install:
  - docker build -t $IMAGE_NAME:latest-travis .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $IMAGE_NAME:latest-travis