version: "1.0"

stages:
  - "build"

steps:
  build:
    title: Building Docker Image
    type: build
    stage: build
    image_name: Dockerfile
    working_directory: ./
    tag: 'multi-stage'
    dockerfile: Dockerfile

      
