    version: 2
    jobs:
      build:
        environment:
          IMAGE_NAME: finstreet/test-deployment
        docker:
          - image: docker:17.05.0-ce-git
        steps:
          - checkout
          - setup_remote_docker
          
          - run:
              name: Build Docker image
              command: docker build -t $IMAGE_NAME:latest .

          - run:
              name: Login Docker
              command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                 
          - run:
              name: Push Docker image
              command: docker push $IMAGE_NAME:latest
          
          - add_ssh_keys:
              fingerprints:
                - "af:06:17:c7:98:0c:6d:b9:51:47:36:39:9a:31:da:9a"

          - run:
              name: Key scan
              command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

          - run:
              name: Deploy over SSH
              command: ssh $SSH_USER@$SSH_HOST 'cd /var/Wordpress/ && ./restart.sh'
          
    workflows:
      version: 2
      build-master:
        jobs:
          - build:
              context: TestDeployment
              filters:
                branches:
                  only: master