    version: 2
    jobs:
      build:
        environment:
          IMAGE_NAME: finstreet/testdeployment
          USERNAME: $DOCKER_USERNAME
          PASSWORD: $DOCKER_PASSWORD
          context: TestDeployment
        docker:
          - image: docker:17.05.0-ce-git
        steps:
          - checkout
          - setup_remote_docker
          
          - run:
              name: Build Docker image
              command: docker build -t $IMAGE_NAME:latest .

          - run:
              name: Login Docker
              command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: master