    version: 2
    jobs:
      build:
        environment:
          IMAGE_NAME: finstreet/test-deployment
        docker:
          - image: docker:17.05.0-ce-git
        steps:
          - checkout
          - setup_remote_docker
        
          
          - add_ssh_keys:
              fingerprints:
                - "56:7b:3d:65:22:31:78:9c:a5:73:80:78:e5:6e:0e:96"

          - run:
              name: Key scan
              command: ssh-keyscan -H 94.130.59.82 >> ~/.ssh/known_hosts

          - run:
              name: Deploy over SSH
              command: ssh $SSH_USER@$SSH_HOST 'cd /var/Wordpress/ && ls -a'


          
    workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: 
                    - master
                    - develop
