    version: 2
    jobs:
      build:
        environment:
          IMAGE_NAME: finstreet/test-deployment
        docker:
          - image: docker:17.05.0-ce-git
        steps:
          - checkout
          - setup_remote_docker
        
          
          - add_ssh_keys:
              fingerprints:
                - "af:06:17:c7:98:0c:6d:b9:51:47:36:39:9a:31:da:9a"

          - run:
              name: Key scan
              command: ssh-keyscan -H 94.130.59.82 >> ~/.ssh/known_hosts

          - run:
              name: Deploy over SSH
              command: ssh $SSH_USER@$SSH_HOST 'cd /var/Wordpress/ && ls -a'


          
    workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: 
                    - master
                    - develop
