name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker build push
      env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
           IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
           
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
           docker build . --tag $IMAGE_NAME:latest
           docker push $IMAGE_NAME:latest
