name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set environment variables
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
        IMAGE_NAME: 'finstreet/test-deployment'
    - name: Docker build
      run: docker build . --tag ${IMAGE_NAME}:latest
    
    - name: Docker login 
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Docker push
      run: docker push ${IMAGE_NAME}:latest
    
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /var/Wordpress/
          ./restart.sh
        host: ${{ secrets.HOST }}
        user: root
        key: ${{ secrets.PRIVATE_KEY}}
