name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag finstreet/test-deployment:latest
    - name: Login to Docker hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
