name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: docker build . --tag finstreet/test-deployment:latest
    - name: Docker login
      env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}      
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Docker push
      run: docker push finstreet/test-deployment:latest
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /tmp
          ls -a
        host: ${{ secrets.HOST }}
        user: root
        key: ${{ secrets.PRIVATE_KEY}}
