name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      env:
          IMAGE_NAME: ${{ finstreet/test-deployment }}
    - name: Build the Docker image
      run: docker build . --tag $IMAGE_NAME:latest
    - name: Login to Docker hub
      env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Push to Docker hub
      run: docker push $IMAGE_NAME:latest
